<<<<<<< HEAD
# Generated by Django 4.2.23 on 2025-07-06 07:12
=======
# Generated by Django 4.2.23 on 2025-07-06 08:30
>>>>>>> 3d3b64351b71ed6ee6d2ebc715735c9e4097aff0

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
<<<<<<< HEAD
        ('quizzes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
=======
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('quizzes', '0001_initial'),
>>>>>>> 3d3b64351b71ed6ee6d2ebc715735c9e4097aff0
    ]

    operations = [
        migrations.AddField(
            model_name='userquizresult',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_quiz_result', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ranking',
            name='school',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='quizzes.school'),
        ),
        migrations.AddField(
            model_name='quizsession',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='quizzes.school'),
        ),
        migrations.AddField(
            model_name='quizsession',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_session', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='choice',
            name='quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='quizzes.quiz'),
        ),
        migrations.AlterUniqueTogether(
            name='userquizresult',
            unique_together={('user', 'quiz')},
        ),
    ]
