# Generated by Django 4.2.23 on 2025-07-06 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0002_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userquizresult',
            unique_together=set(),
        ),
    ]
