# Generated by Django 4.2.23 on 2025-07-03 05:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('history', '0002_schoolscore_remove_historycontent_image_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('quiz_id', models.AutoField(primary_key=True, serialize=False)),
                ('question', models.TextField(null=True)),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='history.historycontent')),
            ],
        ),
        migrations.CreateModel(
            name='QuizOption',
            fields=[
                ('quiz_option_id', models.AutoField(primary_key=True, serialize=False)),
                ('option', models.TextField(null=True)),
                ('is_correct', models.BooleanField(null=True)),
                ('option_order', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=1, null=True)),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quizzes.quiz')),
            ],
        ),
        migrations.CreateModel(
            name='CopyOfQuizOption',
            fields=[
                ('quiz_result_id', models.AutoField(primary_key=True, serialize=False)),
                ('is_correct', models.BooleanField(null=True)),
                ('option_order', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=1, null=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quizzes.quiz')),
                ('quiz_option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quizzes.quizoption')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
