# Generated by Django 4.2.23 on 2025-07-05 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userquizresult',
            name='school',
        ),
        migrations.RemoveField(
            model_name='userquizresult',
            name='user',
        ),
        migrations.DeleteModel(
            name='Choice',
        ),
        migrations.DeleteModel(
            name='Quiz',
        ),
        migrations.DeleteModel(
            name='School',
        ),
        migrations.DeleteModel(
            name='UserQuizResult',
        ),
    ]
