# Generated by Django 4.2.23 on 2025-07-07 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='school',
            name='participant_count',
        ),
    ]
