# Generated by Django 4.2.23 on 2025-07-07 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0003_remove_school_participant_count'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='school',
            options={},
        ),
        migrations.RemoveField(
            model_name='school',
            name='total_score',
        ),
    ]
