<<<<<<< HEAD
# Generated by Django 4.2.23 on 2025-07-06 07:12
=======
# Generated by Django 4.2.23 on 2025-07-06 08:30
>>>>>>> 3d3b64351b71ed6ee6d2ebc715735c9e4097aff0

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
<<<<<<< HEAD
        ('history', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
=======
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('history', '0001_initial'),
>>>>>>> 3d3b64351b71ed6ee6d2ebc715735c9e4097aff0
    ]

    operations = [
        migrations.AddField(
            model_name='usersavedcard',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='usersavedcard',
            unique_together={('user', 'card')},
        ),
    ]
