# Generated by Django 4.2.23 on 2025-07-02 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='category_id',
        ),
    ]
