# Generated by Django 4.2.23 on 2025-07-02 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_category_postcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.ManyToManyField(related_name='posts', through='posts.PostCategory', to='posts.category'),
        ),
    ]
