# Generated by Django 4.2.23 on 2025-07-05 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0011_post_views'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='type',
            field=models.CharField(blank=True, choices=[('현직자', '현직자'), ('취준생', '취준생'), ('기타', '기타')], max_length=10, null=True),
        ),
    ]
