# Generated by Django 4.2.23 on 2025-07-03 05:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_name', models.CharField(max_length=100)),
                ('total_score', models.IntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='historycontent',
            name='image',
        ),
        migrations.RemoveField(
            model_name='userprogress',
            name='is_learned',
        ),
        migrations.RemoveField(
            model_name='userprogress',
            name='last_updated',
        ),
        migrations.AddField(
            model_name='historycontent',
            name='period',
            field=models.CharField(max_length=165, null=True),
        ),
        migrations.AddField(
            model_name='historycontent',
            name='type',
            field=models.CharField(choices=[('인물', '인물'), ('퀴즈', '퀴즈')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='userprogress',
            name='completion',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='userprogress',
            name='percentage',
            field=models.DecimalField(decimal_places=1, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='historycontent',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='historycontent',
            name='title',
            field=models.CharField(max_length=280, null=True),
        ),
        migrations.CreateModel(
            name='HistoryCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True)),
                ('period', models.CharField(max_length=50, null=True)),
                ('role', models.CharField(max_length=100, null=True)),
                ('image_url', models.CharField(max_length=255, null=True)),
                ('info', models.TextField(null=True)),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='history.historycontent')),
            ],
        ),
    ]
