# Generated by Django 4.2.23 on 2025-07-05 07:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('history', '0002_schoolscore_remove_historycontent_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSavedCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saved_at', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='SchoolScore',
        ),
        migrations.RemoveField(
            model_name='userprogress',
            name='content',
        ),
        migrations.RemoveField(
            model_name='userprogress',
            name='user',
        ),
        migrations.RemoveField(
            model_name='historycard',
            name='content',
        ),
        migrations.RemoveField(
            model_name='historycard',
            name='info',
        ),
        migrations.RemoveField(
            model_name='historycard',
            name='period',
        ),
        migrations.RemoveField(
            model_name='historycard',
            name='role',
        ),
        migrations.AddField(
            model_name='historycard',
            name='birth_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historycard',
            name='death_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historycard',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historycard',
            name='era',
            field=models.CharField(default='20세기 초', max_length=100),
        ),
        migrations.AddField(
            model_name='historycard',
            name='region',
            field=models.CharField(default='아시아', max_length=100),
        ),
        migrations.AlterField(
            model_name='historycard',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historycard',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.DeleteModel(
            name='HistoryContent',
        ),
        migrations.DeleteModel(
            name='UserProgress',
        ),
        migrations.AddField(
            model_name='usersavedcard',
            name='card',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='history.historycard'),
        ),
        migrations.AddField(
            model_name='usersavedcard',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='usersavedcard',
            unique_together={('user', 'card')},
        ),
    ]
