# Generated by Django 4.2.23 on 2025-07-05 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_real_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='grade_level',
        ),
        migrations.RemoveField(
            model_name='user',
            name='real_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='school_name',
        ),
    ]
